/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars false --include-runtime false` (hash: b0db472137468775af500f65bb76b21d)
declare namespace Cloudflare {
  interface Env {
    KV: KVNamespace
    GITHUB_SHA: string
    LOGFIRE_TOKEN: string
    LOGFIRE_ENVIRONMENT: string
    OPENAI_API_KEY: string
    GROQ_API_KEY: string
    limitsDB: D1Database
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'GITHUB_SHA' | 'LOGFIRE_TOKEN' | 'LOGFIRE_ENVIRONMENT' | 'OPENAI_API_KEY' | 'GROQ_API_KEY'>
    > {}
}
