/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars false --include-runtime false` (hash: 67942e5edfbb1f8530619b854be1980f)
declare namespace Cloudflare {
  interface Env {
    KV: KVNamespace
    GITHUB_SHA: string
    LOGFIRE_TOKEN: string
    LOGFIRE_ENVIRONMENT: string
    OPENAI_API_KEY: string
    limitsDB: D1Database
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'GITHUB_SHA' | 'LOGFIRE_TOKEN' | 'LOGFIRE_ENVIRONMENT' | 'OPENAI_API_KEY'>
    > {}
}
