/* eslint-disable @typescript-eslint/no-floating-promises */
import { JSONSchema4 } from 'json-schema'
import { compile } from 'json-schema-to-typescript'

import * as fs from 'fs'

const bannerComment =
  '/* eslint-disable */\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,\n* and run `npm run generate-genai-types` to regenerate this file.\n*/'

fetch('https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-output-messages.json').then((res) => {
  res.text().then((content) => {
    const schema = JSON.parse(content) as JSONSchema4
    compile(schema, 'GenAIOutputMessages', { bannerComment }).then((ts) => {
      fs.writeFileSync('src/otel/genai-output-messages.d.ts', ts)
    })
  })
})

fetch('https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-input-messages.json').then((res) => {
  res.text().then((content) => {
    const schema = JSON.parse(content) as JSONSchema4
    compile(schema, 'GenAIInputMessages', { bannerComment }).then((ts) => {
      fs.writeFileSync('src/otel/genai-input-messages.d.ts', ts)
    })
  })
})
