// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD:
// Edit config.yml to configure the gateway, then run `make config` to write this file

import type { Config } from './types'

export const config: Config = {
  org: 'main',
  teams: [
    {
      name: 'default',
      users: [
        {
          name: 'samuel',
        },
      ],
    },
  ],
  providers: [
    {
      name: 'openai',
      baseURL: 'https://api.openai.com/v1',
      proxySchema: 'openai',
      credentials: 'env:OPENAI_API_KEY',
    },
  ],
  apiKeys: [
    {
      team: 'default',
      apiKey: 'testing',
      providers: ['openai'],
    },
  ],
}
